// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npyygkgsqfhfcdulixlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5weXlna2dzcWZoZmNkdWxpeGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTExMDAsImV4cCI6MjA2MzE4NzEwMH0.aLOVAj6MI0itWBAxAtea7D8tDEySGDGksQ5oHk1DwyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);